import type { DeviceInfo } from "./session.types";

export enum SecurityAuditAction {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",
  REGISTRATION = "REGISTRATION",
  LOGOUT = "LOGOUT",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  PASSWORD_RESET = "PASSWORD_RESET",
  FORCE_PASSWORD_RESET = "FORCE_PASSWORD_RESET",
  PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED",
  EMAIL_CHANGE_REQUEST = "EMAIL_CHANGE_REQUEST",
  EMAIL_CHANGE = "EMAIL_CHANGE",
  EMAIL_CHANGE_CONFIRMATION = "EMAIL_CHANGE_CONFIRMATION",
  EMAIL_CHANGE_FAILURE = "EMAIL_CHANGE_FAILURE",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  TWO_FACTOR_AUTH_REQUIRED = "TWO_FACTOR_AUTH_REQUIRED",
  TWO_FACTOR_AUTH_SUCCESS = "TWO_FACTOR_AUTH_SUCCESS",
  SESSION_CREATED = "SESSION_CREATED",
  REVOKE_ALL_SESSIONS = "REVOKE_ALL_SESSIONS",
  SESSION_REVOKED = "SESSION_REVOKED",
  SESSION_TERMINATED = "SESSION_TERMINATED",
  BACKUP_CODE_RECOVERY = "BACKUP_CODE_RECOVERY",
  BACKUP_CODE_REGENERATED = "BACKUP_CODE_REGENERATED",
  BACKUP_CODE_USED = "BACKUP_CODE_USED",
  VERIFICATION_EMAIL_REQUEST = "VERIFICATION_EMAIL_REQUEST",
  VERIFICATION_EMAIL_SENT = "VERIFICATION_EMAIL_SENT",
  VERIFICATION_EMAIL_CONFIRMED = "VERIFICATION_EMAIL_CONFIRMED",
  VERIFICATION_EMAIL_RESENT = "VERIFICATION_EMAIL_RESENT",
  VERIFICATION_EMAIL_FAILED = "VERIFICATION_EMAIL_FAILED",
  VERIFICATION_EMAIL_CODE_RESENT = "VERIFICATION_EMAIL_CODE_RESENT",
  VERIFICATION_EMAIL_CODE_FAILED = "VERIFICATION_EMAIL_CODE_FAILED",
  VERIFICATION_EMAIL_CODE_USED = "VERIFICATION_EMAIL_CODE_USED",
  VERIFICATION_EMAIL_CODE_EXPIRED = "VERIFICATION_EMAIL_CODE_EXPIRED",
  VERIFICATION_EMAIL_CODE_INVALID = "VERIFICATION_EMAIL_CODE_INVALID",
  VERIFICATION_EMAIL_CODE_RECOVERED = "VERIFICATION_EMAIL_CODE_RECOVERED",
  VERIFICATION_EMAIL_CODE_REGENERATED = "VERIFICATION_EMAIL_CODE_REGENERATED",
  VERIFICATION_EMAIL_CODE_RECOVERY_FAILED = "VERIFICATION_EMAIL_CODE_RECOVERY_FAILED",
  VERIFICATION_EMAIL_CODE_RECOVERY_REQUEST = "VERIFICATION_EMAIL_CODE_RECOVERY_REQUEST",
  VERIFICATION_EMAIL_CODE_RECOVERY_SENT = "VERIFICATION_EMAIL_CODE_RECOVERY_SENT",
  VERIFICATION_EMAIL_FAILURE = "VERIFICATION_EMAIL_FAILURE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  SECURITY_ACTION = "SECURITY_ACTION",
  AUDIT_LOG_EXPORT = "AUDIT_LOG_EXPORT",
  AUDIT_LOG_DELETE = "AUDIT_LOG_DELETE",
  AUDIT_LOG_CLEAR = "AUDIT_LOG_CLEAR",
  AUDIT_LOG_VIEW = "AUDIT_LOG_VIEW",
  NEW_DEVICE_ALERT_SENT = "NEW_DEVICE_ALERT_SENT",
  BOT_DETECTED = "BOT_DETECTED",
  IMPOSSIBLE_TRAVEL = "IMPOSSIBLE_TRAVEL",
  IMPOSSIBLE_TRAVEL_ALERT_SENT = "IMPOSSIBLE_TRAVEL_ALERT_SENT",
}
// Enum for maintainability
export enum AuditAction {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  RESTORE = "RESTORE",
  IMAGE_ADD = "IMAGE_ADD",
  IMAGE_REMOVE = "IMAGE_REMOVE",
  STATUS_CHANGE = "STATUS_CHANGE",
  INVENTORY_RESERVATION = "INVENTORY_RESERVATION",
  INVENTORY_RESERVATION_PARTIAL = "INVENTORY_RESERVATION_PARTIAL",
  INVENTORY_RESERVATION_CANCEL = "INVENTORY_RESERVATION_CANCEL",
  CHECKOUT_FAILURE = "CHECKOUT_FAILURE",
  CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS",
  PAYMENT_FAILURE = "PAYMENT_FAILURE",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  REFUND = "REFUND",
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_UPDATED = "ORDER_UPDATED",
  ORDER_DELETED = "ORDER_DELETED",
  ORDER_FAILURE = "ORDER_FAILURE",
  ORDER_STATUS_CHANGE = "ORDER_STATUS_CHANGE",
}
export enum AuditSource {
  WEB = "WEB",
  API = "API",
  SYSTEM = "SYSTEM",
}
export enum EntityType {
  PRODUCT = "PRODUCT",
  USER = "USER",
  ORDER = "ORDER",
}
// audit.types.ts
export interface AuditLogDetails {
  success: boolean;
  device: DeviceInfo;
  // message: string;
  [key: string]: any; // Additional dynamic details
}
export interface ClientAuditLogDetails {
  details: AuditLogDetails;
  action: SecurityAuditAction;
  timestamp: Date;
  // message: string;
}
