import { DeviceInfo } from "./session.types";

export enum AuditAction {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",
  REGISTRATION = "REGISTRATION",
  LOGOUT = "LOGOUT",
  PASSWORD_CHANGE = "PASSWORD_CHANGE",
  PASSWORD_RESET = "PASSWORD_RESET",
  PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
  ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED",
  EMAIL_CHANGE_REQUEST = "EMAIL_CHANGE_REQUEST",
  EMAIL_CHANGE = "EMAIL_CHANGE",
  EMAIL_CHANGE_CONFIRMATION = "EMAIL_CHANGE_CONFIRMATION",
  EMAIL_CHANGE_FAILURE = "EMAIL_CHANGE_FAILURE",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  TWO_FACTOR_AUTH_REQUIRED = "TWO_FACTOR_AUTH_REQUIRED",
  TWO_FACTOR_AUTH_SUCCESS = "TWO_FACTOR_AUTH_SUCCESS",
  SESSION_CREATED = "SESSION_CREATED",
  SESSION_TERMINATED = "SESSION_TERMINATED",
  BACKUP_CODE_RECOVERY = "BACKUP_CODE_RECOVERY",
  BACKUP_CODE_REGENERATED = "BACKUP_CODE_REGENERATED",
  BACKUP_CODE_USED = "BACKUP_CODE_USED",
  VERIFICATION_EMAIL_REQUEST = "VERIFICATION_EMAIL_REQUEST",
  VERIFICATION_EMAIL_SENT = "VERIFICATION_EMAIL_SENT",
  VERIFICATION_EMAIL_CONFIRMED = "VERIFICATION_EMAIL_CONFIRMED",
  VERIFICATION_EMAIL_RESENT = "VERIFICATION_EMAIL_RESENT",
  VERIFICATION_EMAIL_FAILED = "VERIFICATION_EMAIL_FAILED",
  VERIFICATION_EMAIL_CODE_RESENT = "VERIFICATION_EMAIL_CODE_RESENT",
  VERIFICATION_EMAIL_CODE_FAILED = "VERIFICATION_EMAIL_CODE_FAILED",
  VERIFICATION_EMAIL_CODE_USED = "VERIFICATION_EMAIL_CODE_USED",
  VERIFICATION_EMAIL_CODE_EXPIRED = "VERIFICATION_EMAIL_CODE_EXPIRED",
  VERIFICATION_EMAIL_CODE_INVALID = "VERIFICATION_EMAIL_CODE_INVALID",
  VERIFICATION_EMAIL_CODE_RECOVERED = "VERIFICATION_EMAIL_CODE_RECOVERED",
  VERIFICATION_EMAIL_CODE_REGENERATED = "VERIFICATION_EMAIL_CODE_REGENERATED",
  VERIFICATION_EMAIL_CODE_RECOVERY_FAILED = "VERIFICATION_EMAIL_CODE_RECOVERY_FAILED",
  VERIFICATION_EMAIL_CODE_RECOVERY_REQUEST = "VERIFICATION_EMAIL_CODE_RECOVERY_REQUEST",
  VERIFICATION_EMAIL_CODE_RECOVERY_SENT = "VERIFICATION_EMAIL_CODE_RECOVERY_SENT",
  VERIFICATION_EMAIL_FAILURE = "VERIFICATION_EMAIL_FAILURE",
}
// audit.types.ts
export interface AuditLogDetails {
  success: boolean;
  device?: Partial<DeviceInfo>;
  [key: string]: any; // Additional dynamic details
}
