// Configuration Constants
export const SECURITY_CONFIG = {
  BACKUP_CODES: 10,
  PBKDF2_ITERATIONS: 10000,
  AES_KEY_LENGTH: 32,
  TOTP_WINDOW: 1,
  MAX_ATTEMPTS: 5,
  LOCKOUT_MINUTES: 15,
  SESSION_DAYS: 30,
};
